<a href="https://colab.research.google.com/github/SonaSojan/healio/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
a=[1,2,3]
b=[4,5,6]
result=[]
for i in range (len(a)):
  result.append(a[i]+b[i])
  print(result)

[5]
[5, 7]
[5, 7, 9]


In [18]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Array a:",a)
print("Array b:",b)
print(a+b)

Array a: [1 2 3]
Array b: [4 5 6]
[5 7 9]


In [19]:

#1 D array
import numpy as np
a=np.array([5,10,15,20])
print(a)
print(type(a))

[ 5 10 15 20]
<class 'numpy.ndarray'>


In [20]:
import numpy as np

In [21]:
#2 D array
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(b)
print(type(b))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>


In [22]:
b=np.array(8)
print(b)
print(type(b))

8
<class 'numpy.ndarray'>


np.array()
np.zeroes()
np.ones()
np.arange() evenly spaced values within a specified range
np.eye() identity matrix

*   List item
*   List item


np.linspace()

In [33]:
print(np.zeros((3,4)))  #3,4 as row and column

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
print(np.zeros((3)))  #3 considered as dimension

[0. 0. 0.]


In [24]:
print(np.ones((3,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
print(np.ones((4)))

[1. 1. 1. 1.]


In [25]:
print(np.arange(1,13,2))

[ 1  3  5  7  9 11]


In [26]:
print(np.arange(2,11,2)) #even numbers

[ 2  4  6  8 10]


In [27]:
print(np.arange(0,20,3)) #multiples of 3

[ 0  3  6  9 12 15 18]


start,stop,number of values -linspace syntax

In [36]:
print(np.linspace(20,60,10))

[20.         24.44444444 28.88888889 33.33333333 37.77777778 42.22222222
 46.66666667 51.11111111 55.55555556 60.        ]


In [29]:
print(np.linspace(10,50,4))

[10.         23.33333333 36.66666667 50.        ]


In [37]:
print(np.linspace(100,500,5))

[100. 200. 300. 400. 500.]


In [30]:
print(np.eye(5,5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
print(np.eye(4,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
